name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Ensure correct branch is checked out
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js v20

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # The folder containing your static files
          allow_empty_commit: true  # This can help if no changes are detected
